### ISSUE TITLE
example manifest README references old bosh.io runc url

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry-attic/cf-release#1113]
I noticed that the README in example manifest reads at [1]:
```
...
bosh upload release https://bosh.io/d/github.com/cloudfoundry-incubator/garden-runc-release
...
```

bosh.io shows that the cloudfoundry-incubator/garden-runc-release hasn't been updated since 1.0.0 but cloudfoundry/garden-runc-release points to 1.0.3 which is the newest release. The README should read:

```
...
bosh upload release https://bosh.io/d/github.com/cloudfoundry/garden-runc-release
...
```

[1] https://github.com/cloudfoundry/cf-release/blob/master/example_manifests/README.md#create-and-deploy-cloud-foundry

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
