### ISSUE TITLE
Need to make TLS versions in HAProxy configurable

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry-attic/cf-release#1204]
We just caused a production downtime after updating to a new version of CF because we have some clients that aren't able to use TLS 1.2 (in our case it was https://stackoverflow.com/questions/29663974/wcf-client-in-net-4-51-how-to-enable-tls-1-2-when-webrequest-is-used) and this commit forced HAProxy to only accept that:

https://github.com/cloudfoundry/cf-release/commit/db20539ffcc15aff69862b77c2493d93e9a7c3d6

This option needs to be configurable and the default can be to disable SSLv3, TLS 1.0, and TLS 1.1 if desired. We just need to be able to turn back on 1.0 and 1.1.  Even worse, the change was not mentioned in the release notes so we missed it, again resulting in the production downtime for customers.  :-(

Aaron

**Comment by dsabeti** [comment]
Hi @amhuber. Thanks for bringing this to our attention.

First, apologies for failing to include this in release notes. My hope has always been that, if we have to make these kinds of changes, that we at least give proper context in the release notes.

As far as the actual request here to allow older versions of TLS for the HAProxy configuration, we'll need to follow the Gorouter's lead: If HAProxy starts accepting older versions of TLS but the Gorouter does not, then connections will fail between the proxy and the router. I see that you've opened a similar issue on the Gorouter. If @shalako and the Routing team sign off allowing older versions of TLS, we can make the parallel change to HAProxy.

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
