### ISSUE TITLE
Downtime during blue-green deploys

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry-attic/cf-release#1219]
This issue is being raised here for awareness, please see https://github.com/cloudfoundry/route-emitter/issues/8

I think Cloud Foundry acceptance tests should include assertions that there is no downtime during blue-green deploys.

Versions affected: cf-release versions v265+ (the route-emitter issue is contained within diego-release v1.19.0+).

**Comment by dsabeti** [comment]
Hi @henrytk. Thanks for surfacing this issue here. It looks like fixes are on the way.

As far as testing in CATs, let me dig in and see if it makes sense to include this in CATs.

**Comment by dsabeti** [comment]
Hey @henrytk, I think it makes sense to add such a test to CATs. We can't prioritize it too soon, but we're hoping to do some refactoring of the test suites in the fall. I've added [a placeholder story](https://www.pivotaltracker.com/story/show/149615397) to capture this need when we get around to that work.

Let me know if there's anything else you'd like to discuss.

**Comment by henrytk** [comment]
Thanks @dsabeti - nothing else to discuss.

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
