### ISSUE TITLE
Add support for custom header parameters for broker endpoints

### ISSUE THREAD

**Issue by jakkahub** [cloudfoundry-attic/cf-release#1245]
We have a service manager that can provision/deprovision services on our cloud platform. We are extending our service manager operations to CloudFoundry with an Open Service broker.

When our service broker is registered with CF platform to make our services and plans available to end users, CF calls our broker endpoint
`GET /v2/catalog`

Our service broker running on our service manager expects an header parameter for authentication along with basic auth parameter. Without the extra header parameter, our endpoints are not accessible and return 401.

We are looking for a solution on how to pass custom header parameters to broker endpoints during registration, so that platform sends it to every endpoint in subsequent requests to broker.

`PUT /v2/service_instances/:instance_id`
`PUT /v2/service_instances/:instance_id/service_bindings/:binding_id`

**Comment by mattmcneeney** [comment]
Hi @jakkahub 
Please could you detail the use case for this more so I can look into how we can help?
Many thanks

**Comment by jakkahub** [comment]
When CF admin registers our service broker in CloudFoundry
`cf create-service-broker SERVICE_BROKER USERNAME PASSWORD URL [--space-scoped]`

`GET /v2/catalog` is called and our service broker receives `Authorization`, `X-Broker-Api-Version` parameters in header. Our broker also need another parameter TENANT_NAME in header.

We are looking for a solution to pass custom header parameter to service broker from CloudFoundry.

**Comment by mattmcneeney** [comment]
Hi Somesh,

This issue <https://github.com/cloudfoundry/cf-release/issues/1245> may be
related as it talks about sending custom headers to broker endpoints (but
in that case the header and value come form the catalog data).

Please could you detail your use case more? What are you using the *TENANT_NAME
*header field for and who is responsible for specifying the value of the
header?

Thanks,
Matt

**Comment by mattmcneeney** [comment]
What are you using the *TENANT_NAME* header field for? If this data is already specified in the catalog data, what do you gain from it being included in the header of every request?

**Comment by jakkahub** [comment]
Our service platform is a multi tenant system and every incoming request should have TENANT_NAME in header for authentication. This applies for all URLs including service broker registration URL and cannot be bypassed.

**Comment by mattmcneeney** [comment]
OK, that makes sense. If the user you care about is the Cloud Foundry user, then as of v2.13 of the Open Service Broker API (released 2 days ago and supported by CF), you can use the **Originating Identity** header that is sent to service brokers on every request.

The cloud controller sends a `X-Broker-API-Originating-Identity` header with the value being the user_id value from the Cloud Foundry JWT token. More information can be found in the [spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#originating-identity) and the [profile](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/profile.md#originating-identity-header) docs.

Does that help at all? Or is there other user-specific information you need for your multi-tenant system?

**Comment by jakkahub** [comment]
We need TENANT_NAME in header for all incoming request to our broker, not just the end-user initiated messages.

**Comment by jakkahub** [comment]
We came up with a requirement from our use case and this is what we looking for.

**Functional requirements for CF to support custom header params**

`cf create-service-broker SERVICE_BROKER USERNAME PASSWORD URL [-H HEADER] [—space-scoped] `
`cf update-service-broker SERVICE_BROKER USERNAME PASSWORD URL [-H HEADER]`

Options
`-H ` 
_Custom headers to include in the request, flag can be specified multiple times_

**CF platform should -**
1. Save header params during create and update of the service broker
2. Include these header params in all endpoint invocations of this broker. e.g during catalog fetch, provision, deprovision, check last operation, bind, unbind and patch.

**Comment by mattmcneeney** [comment]
Adding the CF CLI PM @dkoper who can respond regarding the CLI changes.

Regarding the platform (Cloud Controller) changes, adding PM @zrob to get his feedback on this too.

Zach - the @cloudfoundry/services-api team could take this on at some point in the future (may be early 2018), but wanted to make you aware of this ask in case you've heard this from other places.

**Comment by mattmcneeney** [comment]
@jakkahub I had an idea of how you could get this working without trying to pass a custom header through the CF CLI and Cloud Controller.

Could you use the Basic Auth credentials (username and password) to determine who the broker is being used by? Those credentials are sent on every request to the broker, and your broker could accept multiple sets of credentials.

**Comment by Gerg** [comment]
@jakkahub Is this something that needs to be configured for each individual broker, or is it something that should be configured in the CF deployment and included in all broker requests.

For example (rough idea):
1. Configure the manifest property: `cc.service_brokers.custom_headers` to "TENANT_NAME: my-cf-123"
2. All requests to all brokers will now include the `TENANT_NAME` header

**Comment by jakkahub** [comment]
We need custom header parameter that needs to be configured for each individual broker.

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
