### ISSUE TITLE
URL query parameters to broker endpoints

### ISSUE THREAD

**Issue by jakkahub** [cloudfoundry-attic/cf-release#1246]
How can I pass extra URL query parameters to broker endpoints? 

We have a service manager that can provision/deprovision services on our cloud platform. We are extending our service manager operations to CloudFoundry with an Open Service broker. Cloud Foundry user can provision/deprovision our services through Open Service Broker API.

Deprovision a service on our cloud platform needs some service specific parameters. we are looking for an option to pass these parameters to our service broker either as a payload or as URL query parameters

I have asked this quesion on servicebroker spec and I was asked to post it in CF.
[https://github.com/openservicebrokerapi/servicebroker/issues/319](url)

**Comment by mattmcneeney** [comment]
Hey @jakkahub. Thanks for raising this - I had been meaning to get back to you on the [openservicebroker](https://github.com/openservicebrokerapi/servicebroker/issues/319) issue.

As @duglin mentioned on that thread, sending data (like JSON) on HTTP DELETE requests is not trivial and would require the Cloud Controller to encode these parameters in some query parameter or header, which we wouldn't be keen on supporting.

I could recommend a workaround as follows:
1. When creating or updating a service instance, you could add a new parameter to your service broker (i.e. `skipBackupOnTerminate`) which can be set to `true` or `false` at any time via `cf update-service SERVICE_INSTANCE -c '{"skipBackupOnTerminate": true}'`.
1. Then when the delete request is received, your service broker has already been told how it should behave.

You could use the JSON schemas field that is being added to the catalog data to declare these parameters in advance, which would allow UIs to render fields like this in a form.

Let me know what you think of this, thanks!

**Comment by jakkahub** [comment]
With above provided workaround, our delete operation will become a two step process (update-service & delete-service). We are trying to make our delete in a single step.

**Comment by mattmcneeney** [comment]
@jakkahub I understand. Does that unblock you for now? If so, I can add this to our backlog and prioritise it accordingly. Are you calling the Cloud Controller API directly or using the CF CLI? (Trying to understand the scope of the work that would need to be done to support this)

**Comment by jakkahub** [comment]
All our services are not updateable `plan_updateable: false` and `PATCH` method is not allowed. 
We are using CF CLI for now.

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
