### ISSUE TITLE
Failing deployment terminating SSL/TLS at the Gorouter Only

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-attic/cf-release#1259]
I am trying to implement "Terminating SSL/TLS at the Gorouter Only".I have followed "https://docs.cloudfoundry.org/adminguide/securing-traffic.html#gorouter_term" link to implement it.
I am testing it with the self-signed certificate for test purpose.To generate certificates  I am using the following command.
>sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout apache-selfsigned.key -out apache-selfsigned.crt

After firing above command I am getting two files of key and certificate respectively.
I have implemented those certs in the following section.

properties:
  router:
    tls_pem:
    - |
      -----BEGIN CERTIFICATE-----
      
      -----END CERTIFICATE-----
      -----BEGIN RSA PRIVATE KEY-----
      
      -----END RSA PRIVATE KEY-----
    enable_ssl: true

After implementation, I am facing an issue in deployment.I have attached two files (error log ) for more information.

[gorouter.err.log](https://github.com/cloudfoundry/cf-release/files/1430236/gorouter.err.log)
[gorouter.log](https://github.com/cloudfoundry/cf-release/files/1430237/gorouter.log)

**Comment by dsabeti** [comment]
Hi @cfmagnum. I think you may have a mistake in your syntax. [The job spec has a good example of the required structure for the property](https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/gorouter/spec#L89-L97).

cc @shalako @aaronshurley

**Comment by cfmagnum** [comment]
@dsabeti  Thanks for your information. I have tried with correct syntax now but still, I am facing the same problem.
I wanted to know that whether I am using right command to generate certificates (Want to use self-signed certs).By using below command I am getting 1 cert and 1 private key file.But as per syntax, it is asking 2 certs and 1 private key.
>sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout apache-selfsigned.key -out apache-selfsigned.crt

**Comment by shalako** [comment]
I recommend using certstrap for simple use cases like this. It makes generating certs dead simple:

https://github.com/square/certstrap

**Comment by dsabeti** [comment]
I'm going to close this issue due to inactivity. @cfmagnum, if you still have questions, feel free to open a new issue in the cf-deployment repo, since this one is deprecated.
