### ISSUE TITLE
Smoketest errand is failing after upgrade from v271 to v276.

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry-attic/cf-release#1260]
At the of CF upgrade from v271 to v276 ,facing issue for smoketest errand for logs. 
Even getting error at the time of pushing app as Warning: error tailing logs Timed out waiting for connection to Loggregator (wss://doppler.sys.doamin:4443).

Attaching smoketest error 
![screen shot 11-03-17 at 03 47 pm](https://user-images.githubusercontent.com/13657881/32428116-2cdb279e-c2ea-11e7-96a5-4f948b68c5af.PNG)

**Comment by dsabeti** [comment]
Hey @cfmagnum. Just to double-check, you're running this errand using `bosh run errand ...`, right? (I'm asking because the output looks like you're running the errand locally.)

Also, which IaaS are you deployed to?

**Comment by dsabeti** [comment]
I'll close this issue due to inactivity. @cfmagnum, if you have more questions, go ahead and open a new issue in the cf-deployment repo.
