### ISSUE TITLE
Deploying diego release failed. Error 450001: Action Failed get_task: Task XXXX result: 1 of 1 post-start scripts failed. Failed Jobs: rep.

### ISSUE THREAD

**Issue by parthasarathi204** [cloudfoundry-attic/cf-release#1272]
Failed updating instance cell_z1 > cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0) (canary): Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep. (00:12:02)
Error 450001: Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep.
sys/log/rep/post-start.stderr.log does not show any error.
sys/log/rep/post-start.stdout.log  shows ping failure
Wed Feb 28 16:39:49 UTC 2018: Pinging rep...
Wed Feb 28 16:39:49 UTC 2018: Attempt 1 failed. Trying again...
Wed Feb 28 16:39:50 UTC 2018: Attempt 2 failed. Trying again...
Wed Feb 28 16:39:51 UTC 2018: Attempt 3 failed. Trying again

Wed Feb 28 16:49:48 UTC 2018: Attempt 574 failed. Trying again...
Wed Feb 28 16:49:49 UTC 2018: Timed out pinging rep. Failing post-start.

I have checked out diego version git checkout 12708d5d329e7463458cd1d016d313f2bf266d86
bosh releases as follows
Acting as user 'admin' on 'Bosh Lite Director'

+-------------+---------------+-------------+
| Name        | Versions      | Commit Hash |
+-------------+---------------+-------------+
| cf          | 272+dev.3     | 32b488da+   |
|             | 272+dev.4     | 32b488da+   |
|             | 272+dev.5     | 32b488da+   |
|             | 272+dev.6     | 32b488da+   |
|             | 272+dev.7*    | 32b488da+   |
|             | 272+dev.8*    | 32b488da    |
| cflinuxfs2  | 1.156.0       | 3c0b2cb2+   |
|             | 1.188.0*      | bbad4a7     |
| diego       | 1.26.0+dev.2  | 12708d5d    |
|             | 1.26.0+dev.3* | 12708d5d    |
|             | 1.26.0+dev.4* | 12708d5d+   |
| garden-runc | 1.9.3         | 55956f4     |
|             | 1.11.1*       | 7c00ceb     |
+-------------+---------------+-------------+
Running instances 
bosh vms
Acting as user 'admin' on 'Bosh Lite Director'
Deployment 'cf-warden'

Director task 97

Task 97 done

+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| VM                                                                        | State   | AZ  | VM Type   | IPs          |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+
| api_z1/0 (88b0c7d1-2a17-4110-84df-89b85ad5c51b)                           | running | n/a | large_z1  | 10.244.0.138 |
| blobstore_z1/0 (33105a28-2a99-4a8b-83ad-507e633a15fa)                     | running | n/a | medium_z1 | 10.244.0.130 |
| consul_z1/0 (77965786-8337-4610-824a-75c94fc58cb5)                        | running | n/a | small_z1  | 10.244.0.54  |
| doppler_z1/0 (fa60dbab-8888-4941-9cd8-552104bcdd25)                       | running | n/a | medium_z1 | 10.244.0.142 |
| etcd_z1/0 (258ff228-1c92-4a88-b24b-8cd4755036c1)                          | running | n/a | large_z1  | 10.244.0.42  |
| ha_proxy_z1/0 (0c7d9cb3-9960-4391-a139-0b7869e27a06)                      | running | n/a | router_z1 | 10.244.0.34  |
| loggregator_trafficcontroller_z1/0 (b865c53c-5f21-47ed-af57-1132e682a0f7) | running | n/a | small_z1  | 10.244.0.146 |
| nats_z1/0 (dda1b668-59f8-4068-b1d5-968b3c5defd0)                          | running | n/a | medium_z1 | 10.244.0.6   |
| postgres_z1/0 (d5f26ab4-a900-493f-8d2a-a1bc1276eac0)                      | running | n/a | medium_z1 | 10.244.0.30  |
| router_z1/0 (72133030-0407-4488-8d10-6a5aeb251f2f)                        | running | n/a | router_z1 | 10.244.0.22  |
| uaa_z1/0 (698ca1f3-78b7-4428-94b1-8bc76cb143e6)                           | running | n/a | medium_z1 | 10.244.0.134 |
+---------------------------------------------------------------------------+---------+-----+-----------+--------------+

VMs total: 11
Deployment 'cf-warden-diego'

Director task 98

Task 98 done

+-----------------------------------------------------------+---------+-----+------------------+-------------+
| VM                                                        | State   | AZ  | VM Type          | IPs         |
+-----------------------------------------------------------+---------+-----+------------------+-------------+
| access_z1/0 (ffa054ac-15c8-4bfd-81da-480e56f687bb)        | running | n/a | access_z1        | 10.244.16.7 |
| brain_z1/0 (74883c05-c6f9-43f3-b232-71987beb25a1)         | running | n/a | brain_z1         | 10.244.16.3 |
| cc_bridge_z1/0 (893ed7a9-f0eb-44c9-aa62-644babb83230)     | running | n/a | cc_bridge_z1     | 10.244.16.5 |
| cell_z1/0 (76864bf0-826d-41e0-81df-4ac9bcba8c46)          | failing | n/a | cell_z1          | 10.244.16.4 |
| database_z1/0 (25d214c4-51ac-49a9-8ea9-20f9c48c39d6)      | running | n/a | database_z1      | 10.244.16.2 |
| route_emitter_z1/0 (14ef1242-881f-4bb6-acd2-12b367e208c0) | running | n/a | route_emitter_z1 | 10.244.16.6 |
+-----------------------------------------------------------+---------+-----+------------------+-------------+
 bosh instances --ps
Acting as user 'admin' on deployment 'cf-warden-diego' on 'Bosh Lite Director'

Director task 99

Task 99 done

+------------------------------------------------------------+---------+-----+------------------+-------------+
| Instance                                                   | State   | AZ  | VM Type          | IPs         |
+------------------------------------------------------------+---------+-----+------------------+-------------+
| access_z1/0 (ffa054ac-15c8-4bfd-81da-480e56f687bb)*        | running | n/a | access_z1        | 10.244.16.7 |
|   consul_agent                                             | running |     |                  |             |
|   ssh_proxy                                                | running |     |                  |             |
|   metron_agent                                             | running |     |                  |             |
|   file_server                                              | running |     |                  |             |
+------------------------------------------------------------+---------+-----+------------------+-------------+
| brain_z1/0 (74883c05-c6f9-43f3-b232-71987beb25a1)*         | running | n/a | brain_z1         | 10.244.16.3 |
|   consul_agent                                             | running |     |                  |             |
|   auctioneer                                               | running |     |                  |             |
|   metron_agent                                             | running |     |                  |             |
+------------------------------------------------------------+---------+-----+------------------+-------------+
| cc_bridge_z1/0 (893ed7a9-f0eb-44c9-aa62-644babb83230)*     | running | n/a | cc_bridge_z1     | 10.244.16.5 |
|   consul_agent                                             | running |     |                  |             |
|   stager                                                   | running |     |                  |             |
|   nsync_listener                                           | running |     |                  |             |
|   nsync_bulker                                             | running |     |                  |             |
|   tps_listener                                             | running |     |                  |             |
|   tps_watcher                                              | running |     |                  |             |
|   cc_uploader                                              | running |     |                  |             |
|   metron_agent                                             | running |     |                  |             |
+------------------------------------------------------------+---------+-----+------------------+-------------+
| cell_z1/0 (76864bf0-826d-41e0-81df-4ac9bcba8c46)*          | failing | n/a | cell_z1          | 10.244.16.4 |
|   consul_agent                                             | running |     |                  |             |
|   rep                                                      | failing |     |                  |             |
|   garden                                                   | running |     |                  |             |
|   metron_agent                                             | running |     |                  |             |
+------------------------------------------------------------+---------+-----+------------------+-------------+
| database_z1/0 (25d214c4-51ac-49a9-8ea9-20f9c48c39d6)*      | running | n/a | database_z1      | 10.244.16.2 |
|   consul_agent                                             | running |     |                  |             |
|   bbs                                                      | running |     |                  |             |
|   metron_agent                                             | running |     |                  |             |
+------------------------------------------------------------+---------+-----+------------------+-------------+
| route_emitter_z1/0 (14ef1242-881f-4bb6-acd2-12b367e208c0)* | running | n/a | route_emitter_z1 | 10.244.16.6 |
|   consul_agent                                             | running |     |                  |             |
|   route_emitter                                            | running |     |                  |             |
|   metron_agent                                             | running |     |                  |             |
+------------------------------------------------------------+---------+-----+------------------+-------------+

copying few task log
D, [2018-02-28 16:37:56 #3303588] [canary_update(access_z1/ffa054ac-15c8-4bfd-81da-480e56f687bb (0))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":null,"log":""}, err: , exit_status: pid 3314712 exit 0
D, [2018-02-28 16:37:57 #3303588] [canary_update(cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":null,"log":""}, err: , exit_status: pid 3313836 exit 0
D, [2018-02-28 16:37:57 #3303588] [canary_update(cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0))] DEBUG -- DirectorJobRunner: (0.000222s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (1576, '2018-02-28 16:37:57.582990+0000', 'admin', 'delete', 'vm', 'cf7b7156-d88a-4cad-4584-f2efe44a6e9f', NULL, '92', 'cf-warden-diego', 'cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46', '{}') RETURNING *
D, [2018-02-28 16:37:57 #3303588] [canary_update(cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0))] DEBUG -- DirectorJobRunner: (0.001144s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2018-02-28 16:37:57.587650+0000', 'admin', 'create', 'vm', NULL, NULL, '92', 'cf-warden-diego', 'cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46', '{}') RETURNING *
D, [2018-02-28 16:37:58 #3303588] [canary_update(cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":"76c04146-29e4-4f53-553c-f616f93f8866","error":null,"log":""}, err: , exit_status: pid 3314791 exit 0
D, [2018-02-28 16:37:58 #3303588] [canary_update(cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0))] DEBUG -- DirectorJobRunner: (0.001034s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (1585, '2018-02-28 16:37:58.705712+0000', 'admin', 'create', 'vm', '76c04146-29e4-4f53-553c-f616f93f8866', NULL, '92', 'cf-warden-diego', 'cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46', '{}') RETURNING *
D, [2018-02-28 16:37:58 #3303588] [canary_update(cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":null,"log":""}, err: , exit_status: pid 3315281 exit 0
D, [2018-02-28 16:38:00 #3303588] [canary_update(cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230 (0))] DEBUG -- DirectorJobRunner: (0.000448s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2018-02-28 16:38:00.350546+0000', 'admin', 'delete', 'vm', '309438bf-df3b-4eb4-6829-f76d6fcbbec4', NULL, '92', 'cf-warden-diego', 'cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230', '{}') RETURNING *
D, [2018-02-28 16:38:01 #3303588] [canary_update(cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230 (0))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":null,"log":""}, err: , exit_status: pid 3315778 exit 0
D, [2018-02-28 16:38:01 #3303588] [canary_update(cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230 (0))] DEBUG -- DirectorJobRunner: (0.001271s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (1587, '2018-02-28 16:38:01.499512+0000', 'admin', 'delete', 'vm', '309438bf-df3b-4eb4-6829-f76d6fcbbec4', NULL, '92', 'cf-warden-diego', 'cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230', '{}') RETURNING *
D, [2018-02-28 16:38:01 #3303588] [canary_update(cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230 (0))] DEBUG -- DirectorJobRunner: (0.000321s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2018-02-28 16:38:01.510477+0000', 'admin', 'create', 'vm', NULL, NULL, '92', 'cf-warden-diego', 'cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230', '{}') RETURNING *
D, [2018-02-28 16:38:02 #3303588] [canary_update(cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230 (0))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":"a546291b-7535-44b4-69ad-d73c3ad32947","error":null,"log":""}, err: , exit_status: pid 3316672 exit 0
D, [2018-02-28 16:38:02 #3303588] [canary_update(cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230 (0))] DEBUG -- DirectorJobRunner: (0.000268s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (1589, '2018-02-28 16:38:02.369533+0000', 'admin', 'create', 'vm', 'a546291b-7535-44b4-69ad-d73c3ad32947', NULL, '92', 'cf-warden-diego', 'cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230', '{}') RETURNING *
D, [2018-02-28 16:38:02 #3303588] [canary_update(cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230 (0))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":null,"log":""}, err: , exit_status: pid 3317990 exit 0
D, [2018-02-28 16:38:31 #3303588] [canary_update(route_emitter_z1/14ef1242-881f-4bb6-acd2-12b367e208c0 (0))] DEBUG -- DirectorJobRunner: (0.000196s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (1570, '2018-02-28 16:38:31.292115+0000', 'admin', 'recreate', 'instance', 'route_emitter_z1/14ef1242-881f-4bb6-acd2-12b367e208c0', NULL, '92', 'cf-warden-diego', 'route_emitter_z1/14ef1242-881f-4bb6-acd2-12b367e208c0', '{}') RETURNING *
D, [2018-02-28 16:38:37 #3303588] [canary_update(access_z1/ffa054ac-15c8-4bfd-81da-480e56f687bb (0))] DEBUG -- DirectorJobRunner: (0.001684s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (1571, '2018-02-28 16:38:37.773787+0000', 'admin', 'recreate', 'instance', 'access_z1/ffa054ac-15c8-4bfd-81da-480e56f687bb', NULL, '92', 'cf-warden-diego', 'access_z1/ffa054ac-15c8-4bfd-81da-480e56f687bb', '{}') RETURNING *
D, [2018-02-28 16:38:42 #3303588] [canary_update(cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230 (0))] DEBUG -- DirectorJobRunner: (0.000298s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (1573, '2018-02-28 16:38:42.746341+0000', 'admin', 'recreate', 'instance', 'cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230', NULL, '92', 'cf-warden-diego', 'cc_bridge_z1/893ed7a9-f0eb-44c9-aa62-644babb83230', '{}') RETURNING *
D, [2018-02-28 16:49:49 #3303588] [canary_update(cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0))] DEBUG -- DirectorJobRunner: (0.006337s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (1572, '2018-02-28 16:49:49.259077+0000', 'admin', 'recreate', 'instance', 'cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46', 'Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep.', '92', 'cf-warden-diego', 'cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46', '{}') RETURNING *
D, [2018-02-28 16:49:49 #3303588] [] DEBUG -- DirectorJobRunner: (0.002540s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1519836589,"stage":"Updating instance","tags":["cell_z1"],"total":1,"task":"cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0) (canary)","index":1,"state":"failed","progress":100,"data":{"error":"Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep."}}
D, [2018-02-28 16:49:49 #3303588] [task:92] DEBUG -- DirectorJobRunner: (0.000873s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2018-02-28 16:49:49.300690+0000', 'admin', 'release', 'lock', 'lock:deployment:cf-warden-diego', NULL, '92', 'cf-warden-diego', NULL, '{}') RETURNING *
I, [2018-02-28 16:49:49 #3303588] [task:92]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2018-02-28 16:49:49 #3303588] [task:92] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"0fe20893-86cc-4193-9992-8e58137bc56c","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'cf-warden-diego' against Director '780a48f4-2d4a-45d9-871f-0cb7c4df3474': #<Bosh::Director::RpcRemoteException: Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep.>","created_at":1519836589,"deployment":"cf-warden-diego"}
D, [2018-02-28 16:49:49 #3303588] [task:92] DEBUG -- DirectorJobRunner: (0.003770s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (1541, '2018-02-28 16:49:49.311274+0000', 'admin', 'update', 'deployment', 'cf-warden-diego', 'Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep.', '92', 'cf-warden-diego', NULL, '{"before":{"releases":["garden-runc/1.11.1","cflinuxfs2/1.188.0","cf/272+dev.8","diego/1.26.0+dev.3"],"stemcells":["bosh-warden-boshlite-ubuntu-trusty-go_agent/3541.4"]},"after":{"releases":["garden-runc/1.11.1","cflinuxfs2/1.188.0","cf/272+dev.8","diego/1.26.0+dev.3","diego/1.26.0+dev.4"],"stemcells":["bosh-warden-boshlite-ubuntu-trusty-go_agent/3541.4"]}}') RETURNING *
D, [2018-02-28 16:49:49 #3303588] [task:92] DEBUG -- DirectorJobRunner: (0.001606s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1519836589,"error":{"code":450001,"message":"Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep."}}
D, [2018-02-28 16:49:49 #3303588] [task:92] DEBUG -- DirectorJobRunner: (0.001134s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2018-02-28 16:49:49.365045+0000', "description" = 'create deployment', "result" = 'Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep.', "output" = '/var/vcap/store/director/tasks/92', "checkpoint_time" = '2018-02-28 16:49:20.972052+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'cf-warden-diego', "started_at" = '2018-02-28 16:36:20.797584+0000', "event_output" = '{"time":1519835780,"type":"deprecation","message":"Ignoring cloud config. Manifest contains ''networks'' section."}
{"time":1519836589,"stage":"Updating instance","tags":["cell_z1"],"total":1,"task":"cell_z1/76864bf0-826d-41e0-81df-4ac9bcba8c46 (0) (canary)","index":1,"state":"failed","progress":100,"data":{"error":"Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep."}}
{"time":1519836589,"error":{"code":450001,"message":"Action Failed get_task: Task 6ce2deb4-97d9-4156-4907-421d8e188e7c result: 1 of 1 post-start scripts failed. Failed Jobs: rep."}}

**Comment by dsabeti** [comment]
Hey @parthasarathi204. cf-release is no longer supported. Please upgrade to [cf-deployment](https://github.com/cloudfoundry/cf-deployment). You can find some information about migrating from cf-release to cf-deployment in our [cf-deployment-transition](https://github.com/cloudfoundry/cf-deployment-transition) repo.
