### ISSUE TITLE
Application push on cloud foundry fails with the following error :The Routing API is currently unavailable

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry-attic/cf-release#1274]
This is our current cf configurations

 cf version: v281
tcp-routing-version : 0.146.0 

When trying to push application on cloud foundry, I am getting the following error :

Unexpected Response
Response code: 503
CC code:       
CC error code: CF-RoutingApiUnavailable
Request ID:    
Description:   The Routing API is currently unavailable
FAILED

The logs from the API VM is mentioned below

**{"timestamp":1521016234.5023994,"message":"Request failed: 503: {\"description\"=>\"The Routing API is currently unavailable\", \"error_code\"=>\"CF-RoutingApiUnavailable\", \"code\"=>370001, \"test_mode_info\"=>{\"description\"=>\"The Routing API is currently unavailable\", \"error_code\"=>\"CF-RoutingApiUnavailable\", \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/05073173cd0c524a817696ea213109a85bdd05f8/cloud_controller_ng/app/controllers/runtime/shared_domains_controller.rb:66:in `rescue in enumerate_shared_domains'\",**
\"/var/vcap/data/packages/cloud_controller_ng/05073173cd0c524a817696ea213109a85bdd05f8/cloud_controller_ng/app/controllers/runtime/shared_domains_controller.rb:57:in `enumerate_shared_domains'\", \"/var/vcap/data/packages/cloud_controller_ng/05073173cd0c524a817696ea213109a85bdd05f8/cloud_controller_ng/app/controllers/base/base_controller.rb:78:in `dispatch'\", \"/var/vcap/data/packages/cloud_controller_ng/05073173cd0c524a817696ea213109a85bdd05f8/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1610:in `block in compile!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_op

Also checked into the go router logs of the routing API VM, got the following error

**memberlist: failed to receive: Encryption is configured but remote state is not encrypted from=IP:port no.**

After changing the routing API parameter to false from the cf-manifest we are now able to push our application successfully, except the applications that use the tcp domain.

Can you suggest us on how to proceed ahead with the troubleshooting and help us in fixing the issue.

**Comment by dsabeti** [comment]
Hi @lordcf, these versions of Cloud Foundry are no longer supported, so I don't think we'll be able to help too much.

I took a look at the old docs, and found the following this:
- [Instructions for deploying routing-release](https://github.com/cloudfoundry/routing-release/tree/0.146.0#deploying-routing-release)
- [Instructions for updating cf-release deployment after deploying routing-release](https://github.com/cloudfoundry/routing-release/tree/0.146.0#post-deploy-steps)

**Comment by lordcf** [comment]
@dsabeti : Thanks for response.
