### ISSUE TITLE
CF-Push Acceptance Tests Fails with "error_code": "CF-StagerUnavailable"  "code": 170010

### ISSUE THREAD

**Issue by sconrod-tester** [cloudfoundry-attic/cf-release#1275]
Stopping app...

Staging app and tracing logs...
Unexpected Response
Response code: 503
CC code:       0
CC error code:
Request ID:    cd9a7edd-7798-4459-6347-360bca414cc3::1baf8b17-2146-48a7-8c5e-ab40b8ea1f73
Description:   {
  "description": "Stager is unavailable: getaddrinfo: Name or service not known (bbs.service.cf.internal:8889)",
  "error_code": "CF-StagerUnavailable",
  "code": 170010
}

FAILED

**Comment by dsabeti** [comment]
Hi @sconrod-tester. This repo has been deprecated for a few months now, so we're no longer supporting it. Please migrate to [cf-deployment](https://github.com/cloudfoundry/cf-deployment) -- you can find tools for doing so [here](https://github.com/cloudfoundry/cf-deployment-transition)

**Comment by sconrod-tester** [comment]
Hi dsabeti, according to the link you sent, bbl can can only be used with:GCP or AWS - bbl only supports these. But actually what I am trying to do is just spin up a small test environment using bosh lite and oracle vmbox. I was following this article [https://grahamnicol.wordpress.com/2017/05/04/deploying-cloud-foundry-on-vagrant-on-virtualbox-on-windows-10/] which works up to the point where I try to cf push an app like spring music then fails with the error. Suggestions?

**Comment by dsabeti** [comment]
Hi @sconrod-tester. You can follow these docs for setting up a local bosh-lite with VirtualBox: https://bosh.io/docs/bosh-lite.html

Once you have your local bosh-lite set up, try these instructions for deploying cf-deployment: https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md
