### ISSUE TITLE
CF-Push Acceptance Tests Fails with "error_code": "CF-StagerUnavailable" "code": 170010 #1275 

### ISSUE THREAD

**Issue by sconrod-tester** [cloudfoundry-attic/cf-release#1276]
CF-Push Acceptance Tests Fails with "error_code": "CF-StagerUnavailable" "code": 170010

Hi dissue closed without properly understanding issue or resolving it. According to the link supplied , bbl can can only be used with:GCP or AWS - bbl only supports these. But actually what I am trying to do is just spin up a small test environment using bosh lite and oracle vmbox. I was following this article [https://grahamnicol.wordpress.com/2017/05/04/deploying-cloud-foundry-on-vagrant-on-virtualbox-on-windows-10/] which works up to the point where I try to cf push an app like spring music then fails with the error. Suggestions?
https://github.com/cloudfoundry-attic/cf-release/issues/1275 - original issue still open.
Please note not using GCP or AWS just using local test environment. This is Win 10 running Oracle VBox. Running the boshlite vagrant box.

**Comment by dsabeti** [comment]
Hi @sconrod-tester. You can follow these docs for setting up a local bosh-lite with VirtualBox: https://bosh.io/docs/bosh-lite.html

Once you have your local bosh-lite set up, try these instructions for deploying cf-deployment: https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md
