### ISSUE TITLE
About cc_service_key_client property when upgrade Cloud Foundry from cf-release v272 to cf-release v287 on openstack

### ISSUE THREAD

**Issue by ngocvanho** [cloudfoundry-attic/cf-release#1277]
Dear
I have deployment Cloud Foundry cf-release  v272 on OpenStack. Currently, I want to upgrade cf-release v287. 
In the document at link: 
https://github.com/cloudfoundry-attic/cf-release/releases?after=v278#v275-job-spec-changes 
have introduces a new UAA client: properties.uaa.clients.cc_service_key_client.secret.
I tried to find this property in template/cf.yml:

cc_service_key_client:
        authorities: credhub.read,credhub.write
        authorized-grant-types: client_credentials
        secret: (( merge ))

What is property used for?
How to generate secret?
or suggestion for me related documents to generate secret for deployment.
if possible please help me.

Thank you very much!

**Comment by dsabeti** [comment]
Hi @ngocvanho. Any string would suffice for that secret, but I'd advise using a generic password generator.

Also, this repo is no longer supported. Please migrate to [cf-deployment](https://github.com/cloudfoundry/cf-deployment). As such, I'm going to close this issue.

For information on migrating, please look [here](https://github.com/cloudfoundry/cf-deployment-transition).
