### ISSUE TITLE
Getting CF-StatsUnavailable error after enabling the temporary_local_tps features flag

### ISSUE THREAD

**Issue by ishwarps** [cloudfoundry-attic/cf-release#1278]
Hello Everyone , we are deploying on  cf(bosh-lite) v283 enabling mtls between cc and diego following the offical documents 
    https://docs.google.com/document/d/1pdxC1DqROqk72BDw--6b5v2r0K7Jpp9l-FbO6tlkQDs/edit#
    Based on docs, when we are enabling cc.diego.temporary_local_tps to true , and tps_listener to false then we are getting following error on CF CLI : with commands, cf push, cf restage, cf restart.
    Unexpected Response
    Response code: 503
    CC code: 200002
    CC error code: CF-StatsUnavailable
    Request ID: 008c1cc5-f6db-4634-78f4-5dd727a6f564::e4fd1b64-f71d-405e-bcdd-a39ebb577713
    Description: Stats unavailable: Stats server temporarily unavailable.
    FAILED

    I have this logs from capi logs. 
    "220 {"timestamp":1526016067.1157424,"message":"stats_for_app.error","log_level":"error","source":"cc.diego.instances_reporter","data":{"request_guid":"e2db58ba-d693-4d91-4349-25009a540f41::299cdba7-2b0e-48b7-a8dc-f60446332dee","error":"getaddrinfo: Name or service not known (loggregator-trafficcontroller.service.cf.internal:8081)"},"thread_id":47327927187940,"fiber_id":47327930600040,"process_id":171253,"file":"/var/vcap/data/packages/cloud_controller_ng/787a262430d55026f39a1342e3305f5a023d9e2b/cloud_controller_ng/lib/cloud_controller/die        go/instances_reporter.rb","lineno":152,"method":"rescue in stats_for_app"}"

I have also checked all process is running on loggregator_trafficcontroller.

Process 'consul_agent'              running
Process 'loggregator_trafficcontroller' running
Process 'metron_agent'              running
Process 'route_registrar'           running
Process 'toolbelt'                  running
System 'system_localhost'           running

The consul logs from job "loggregator_trafficcontroller" is also displaying registering with consul server:
2018/05/11 12:24:42 [INFO] agent: Synced service 'loggregator_trafficcontroller' 

Note: I have enable all features flag and its working except temporary_local_tps.

Any suggestion? @dsabeti  @emalm  - it will be helpful, i am stuck at this issue . my deployment is not going through - enabling the mTLS.

I have checked the process running on loggregator_trafficcontroller vms. its not displaying the 8081 port . is it reason?

![screen shot 05-14-18 at 08 13 pm](https://user-images.githubusercontent.com/7974404/40004537-8a56a9da-57b3-11e8-8208-00ee3275e9a0.PNG)

**Comment by heyjcollins** [comment]
Hey @ishwarps  -- cf-release is no longer supported. Instead, please use [cf-deployment](https://github.com/cloudfoundry/cf-deployment) to deploy (mTLS is enabled by default in cf-deployment).

If you have issues/questions, please reach out to us on CloudFoundry slack: the [#cf-deployment channel](https://cloudfoundry.slack.com/messages/C2U7KA7M4/?)

**Comment by ishwarps** [comment]
Hello @heyjcollins 

yes we understand the CF-release is no longer supported and it has reached EOL . if we understand last version supported should be v287. [please correct me if i am not in sync]
we are in transition to CF-deployment simultaneously.
Before migration, this is final CF release version we are deploying with mTLS[which is also a pre-requisites of cf deployment]. 
while trying the steps mentioned in the release notes : we got stuck at this step. 

From the compatibility matrix, we are sure : we are trying right version of Cf, diego, etc. 

still tps listener and tps watcher is giving troublesome , while deploying & enabling mTLS.  We traced out more and found the following errors on the capi logs 

{"timestamp":1526016067.1157424,"message":"stats_for_app.error","log_level":"error","source":"cc.diego.instances_reporter","data":{"req uest_guid":"e2db58ba-d693-4d91-4349-25009a540f41::299cdba7-2b0e-48b7-a8dc-f60446332dee","error":"getaddrinfo: Name or service not known (loggregator-trafficcontroller.service.cf.internal:8081)"},"thread_id":47327927187940,"fiber_id":47327930600040,"process_id":171253,"f ile":"/var/vcap/data/packages/cloud_controller_ng/787a262430d55026f39a1342e3305f5a023d9e2b/cloud_controller_ng/lib/cloud_controller/die go/instances_reporter.rb","lineno":152,"method":"rescue in stats_for_app"}

Any suggestion?

**Comment by ishwarps** [comment]
closing this issue. As I have given name different in loggregator consul agent .
