### ISSUE TITLE
Migration from CF Releases to CF Deployments

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry-attic/cf-release#1280]
Currently, we are using CF release version 283 and TCP Routing release version 163, with current configuration can we migrate to CF deployments.

If yes, then what are the prerequisites needed to migrate to cf-deployments.?

If not, then what is the compatible version for CF release version with TCP Routing release version to migrate to CF deployments.

**Comment by heyjcollins** [comment]
Hey @lordcf - Please take a look at the [cf-deployment-transition](https://github.com/cloudfoundry/cf-deployment-transition). It should help you migrate from cf-release to cf-deployment. 

If you have further questions, please feel free to reach out to the [cf-deployment channel in CloudFoundry slack](https://cloudfoundry.slack.com/messages/C2U7KA7M4/convo/C2U7KA7M4-1527059149.000031/).

Thanks for reaching out!

Josh

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
