### ISSUE TITLE
Issue Pushing app using CF

### ISSUE THREAD

**Issue by DeshanNaidoo** [cloudfoundry-attic/cf-release#1281]
Request error: Get https://api.ng.bluemix.net/v2/info: dial tcp 104.127.117.143:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
