### ISSUE TITLE
Error 400007: 'nfs_z1/0  is not running after update. Review logs for failed jobs: rpc_nfsd, rpc_mountd

### ISSUE THREAD

**Issue by ngocvanho** [cloudfoundry-attic/cf-release#1282]
Hi All,
I have deployed cloud foundry version 287 on bosh-lite. Currently, I'm deploying job nfs_z1 and an error has occurred.
Failed: 'nfs_z1/0 (de0bbc06-c0fb-4efa-b919-6258cfc1a73e)' is not running after update. Review logs for failed jobs: rpc_nfsd, rpc_mountd (00:03:45)
I don't know how to deploy this job. What do we need to deploy this job?
Please help me resolve it.
Bellow is manifest file and error file
[cf.txt](https://github.com/cloudfoundry-attic/cf-release/files/2188396/cf.txt)
[rpc_mountd_ctl_error.txt](https://github.com/cloudfoundry-attic/cf-release/files/2188405/rpc_mountd_ctl_error.txt)

**Comment by ytulsiani** [comment]
Hey @ngocvanho,

We have stopped supporting `cf-release`. We recommend that you upgrade to [cf-deployment](https://github.com/cloudfoundry/cf-deployment). Here are some [instructions](https://github.com/cloudfoundry/cf-deployment-transition) to help you transition over. If you have any issues, you can ping us on slack!

Cheers,
Yash & Sebastian

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
