### ISSUE TITLE
cloud_controller_ng fails with remote Postgres

### ISSUE THREAD

**Issue by rokejung** [cloudfoundry-attic/cf-release#1284]
This seems related to https://github.com/cloudfoundry-attic/cf-release/issues/159. 

If the Cloud Controller uses external Postgres as its database, the deploy will fail. I had to manually create citext extension in the remote database for the deployment to work. I guess this issue was fixed for local Postgres using https://github.com/cloudfoundry-attic/cf-release/issues/159 but never fixed for external Postgres.

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
