### ISSUE TITLE
Consul ports missing for OpenStack in docs

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-attic/cf-release#959]
When deploying 234, we had problem with service discovery via consul. It turned out the changes regarding additional ports for UDP are not added to the documentation (http://docs.cloudfoundry.org/deploying/openstack/security_group.html). What we added was:

```
Ingress IPv4    UDP 8300 - 8303 0.0.0.0/0 
```

**Comment by DennisDenuto** [comment]
Hi @jhiemer,
We are coincidentally refreshing our openstack environment. As such we will be revisiting our security group rules from our cf docs.

If we find we require ingress rules for consul we will update the docs accordingly.

**Comment by davewalter** [comment]
This repository is no longer supported. Closing issue.
